version: '3.9' 

services:
  php-env:
    build: . #path to dockerfile
    volumes: 
      - ./src:/var/www/html 
    ports:
      - 8080:80
  
  mysql_db:
    image: mysql:8.0.37-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes: 
      - /var/lib/docker/volumes/volume1
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1